import React from 'react';

export function DocumentHeader({ title }: { title?: string }) {
  return (
    <div style={{ textAlign: 'center', marginBottom: '32px', borderBottom: '2px solid var(--gov-blue)', paddingBottom: '24px' }}>
      <div style={{ display: 'flex', justifyContent: 'center', alignItems: 'center', gap: '16px', marginBottom: '16px' }}>
        {/* Official Logo */}
        <div style={{ 
          width: '80px', height: '80px', 
          border: '3px solid var(--muted-gold)', 
          borderRadius: '50%', 
          display: 'flex', justifyContent: 'center', alignItems: 'center', 
          backgroundColor: '#fff',
          boxShadow: 'inset 0 0 10px rgba(197, 168, 128, 0.2)',
          padding: '4px',
          overflow: 'hidden'
        }}>
          <img src="/logo.png" alt="Logo" style={{ width: '100%', height: '100%', objectFit: 'contain' }} />
        </div>
        
        <div style={{ textAlign: 'left' }}>
          <h1 style={{ margin: '0 0 4px 0', color: 'var(--gov-blue)', fontSize: '1.8rem', letterSpacing: '2px', fontFamily: 'var(--font-family-serif)' }}>
            PAZAMAYI SHERIYAYI
          </h1>
          <div style={{ color: 'var(--muted-gold)', fontSize: '0.9rem', letterSpacing: '4px', textTransform: 'uppercase', fontWeight: 'bold' }}>
            Identify • Analyse • Verify
          </div>
        </div>
      </div>
      
      {title && (
        <h2 style={{ margin: '16px 0 0 0', fontSize: '1.5rem', textTransform: 'uppercase', color: 'var(--text-dark)', letterSpacing: '1px' }}>
          {title}
        </h2>
      )}
    </div>
  );
}

export function DocumentFooter({ documentNumber, qrReference }: { documentNumber: string, qrReference?: string }) {
  return (
    <div style={{ marginTop: '40px', borderTop: '2px solid var(--gov-blue)', paddingTop: '16px', display: 'flex', justifyContent: 'space-between', alignItems: 'flex-end', fontSize: '0.8rem', color: 'var(--text-light)' }}>
      <div>
        <div style={{ fontWeight: 'bold', color: 'var(--gov-blue)' }}>{documentNumber}</div>
        <div>Digitally generated by Banana Documentation Division</div>
        <div style={{ fontStyle: 'italic', marginTop: '4px' }}>This is a fictional digital registry system and is not an official government service.</div>
      </div>
      {qrReference && (
        <div style={{ textAlign: 'center' }}>
          <div style={{ width: '80px', height: '80px', backgroundColor: '#000', margin: '0 auto 4px auto', display: 'flex', justifyContent: 'center', alignItems: 'center' }}>
             {/* Fake QR visual block */}
             <div style={{ width: '70px', height: '70px', backgroundColor: '#fff', display: 'grid', gridTemplateColumns: 'repeat(5, 1fr)', gap: '2px', padding: '2px' }}>
                 {Array.from({ length: 25 }).map((_, i) => <div key={i} style={{ backgroundColor: ((i * 7) % 11) > 5 ? '#000' : '#fff' }} />)}
             </div>
          </div>
          <div style={{ fontFamily: 'monospace', fontSize: '0.7rem' }}>SCAN TO VERIFY</div>
        </div>
      )}
    </div>
  );
}
